global class POSobject {

	global String ChannelId {get; set;}
    global Integer CurrentStoreCount {get; set;}
    global String EndDate {get; set;}
    global String Item {get; set;}
    global String Model {get; set;}    
    global Integer OnHandQty {get; set;}
    global String RetailerId {get; set;}    
    global Integer ReturnQty {get; set;}    
    global String SKU {get; set;}    
    global Integer SellThruQty {get; set;}    
    global String StartDate {get; set;}     
    global Integer TraitedStoreCount {get; set;}   
    global Integer Week {get; set;}   
    global Integer Year {get; set;}       

}