/***************************************************************************
Created By : Henry Akpala
Created Date : 
Description : This is a class object for managing error messages
********************************************/
public class VizioSupport_ErrorObj{
    
    public Integer ErrCode;
    public String ErrMsg;
    public String ErrBody;
    public String ErrStatus;
    public String ErrFolder;
    
    public VizioSupport_ErrorObj(){
    
    }
    

}