/**
 *  This class is called by the Trigger RelatedClaimTrigger
 *	It creates a Case, SR and Child Line Items whenever a Service_Claim__C
 *	from the Record Type RMA or warranty is Approved
 *
 * @author              Cristian Torres
 * @version             1.0
 * @since               1.0
 */ 
public with sharing class VizioSupport_ServiceClaim_CaseCreation 
{
	
	/**
     * Constructor
     *
     * @param        
     * @return                
     * @since   1.0                                                                       
     */ 
	public VizioSupport_ServiceClaim_CaseCreation() 
	{
		
	}


	/**
     *  
     *
     * @param   //Phone in any format  
     * @return                
     * @since   1.0                                                                       
     */ 
	public void createCaseSRandLI()
	{

	}

}